import DesktopIcon from "@icons/DesktopIcon";
import FilterIcon from "@icons/FilterIcon";
import MobileIcon from "@icons/MobileIcon";
import LaunchIcon from "@mui/icons-material/Launch";
import { IconButton, TextField } from "@mui/material/";
import { Box } from "@mui/system";
import { GridColDef, GridRenderCellParams } from "@mui/x-data-grid";
import { randomCreatedDate } from "@mui/x-data-grid-generator";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  FunctionComponent,
  JSXElementConstructor,
  ReactElement,
  ReactFragment,
  ReactPortal,
  SVGProps,
} from "react";
import { DashboardTab } from "types/dashboard";
import MaskedData from "@components/common/MaskedData";
import { MaskType } from "@utils/maskingUtils";
interface IProps {
  id?: string;
  full_name?: string;
  pan_number?: string;
  disabled?: boolean;
  product_code?: any;
}

export const ShowIcon: FunctionComponent<SVGProps<SVGSVGElement>> = (props) => {
  return (
    <svg
      width="17"
      height="17"
      viewBox="0 0 13 13"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M7.74238 1.45114C7.35428 1.45114 7.03968 1.13652 7.03968 0.748437C7.03968 0.360351 7.35428 0.0457382 7.74238 0.0457382H11.9586C12.1449 0.0457382 12.3237 0.119775 12.4555 0.251552C12.5872 0.383336 12.6613 0.562067 12.6613 0.748437V4.96463C12.6613 5.35273 12.3467 5.66733 11.9586 5.66733C11.5705 5.66733 11.2559 5.35273 11.2559 4.96463V2.44491L4.72577 8.975C4.45135 9.24941 4.00643 9.24941 3.732 8.975C3.45758 8.7006 3.45758 8.25565 3.732 7.98125L10.2621 1.45114H7.74238ZM0.0126953 2.85653C0.0126953 2.08035 0.641913 1.45114 1.41809 1.45114H4.93159C5.31969 1.45114 5.63429 1.76575 5.63429 2.15383C5.63429 2.54192 5.31969 2.85653 4.93159 2.85653H1.41809V11.2889H9.85048V7.77543C9.85048 7.38733 10.1651 7.07273 10.5532 7.07273C10.9413 7.07273 11.2559 7.38733 11.2559 7.77543V11.2889C11.2559 12.0651 10.6267 12.6943 9.85048 12.6943H1.41809C0.641913 12.6943 0.0126953 12.0651 0.0126953 11.2889V2.85653Z"
        fill="#424242"
      />
    </svg>
  );
};

export const LinkComponent = ({ id, full_name, pan_number, disabled, product_code }: IProps) => {
  const router = useRouter();
  return (
    <Link
      href={{
        pathname: "/dashboard/users/[userid]/",
        query: {
          stage: DashboardTab.BASIC_DETAILS,
          userid: id,
          name: full_name,
          pan: pan_number,
          product: product_code,
        },
      }}
      passHref
    >
      <IconButton component="a" disabled={disabled}>
        <LaunchIcon color="primary" />
      </IconButton>
    </Link>
  );
};

const FilterComponent = (props: {
  children:
    | string
    | number
    | boolean
    | ReactElement<any, string | JSXElementConstructor<any>>
    | ReactFragment
    | ReactPortal
    | null
    | undefined;
}) => {
  return (
    <Box
      sx={{
        display: "flex",
        justifyContent: "space-between",
        gap: 2,
      }}
    >
      {props.children}
    </Box>
  );
};

function renderImage(params: GridRenderCellParams<string>) {
  const device = params.value;
  const id = params.id;
  if (device === "mobile" && id != 101) return <MobileIcon />;
  else if (id != 101) return <DesktopIcon />;
}

const searchComponent = () => {
  return <TextField type="search" />;
};

export const columns: GridColDef[] = [
  {
    field: "show",
    headerName: "Show",
    width: 70,
    renderCell: (params) => <LinkComponent id={params.row.id} />,
    renderHeader: () => (
      <>
        {"Show "}
        <FilterIcon />
      </>
    ),
  },
  {
    field: "device",
    headerName: "Device",
    width: 70,
    // renderCell: () => {
    //   return <MobileComponent />;
    // },
    renderCell: renderImage,
  },
  { field: "verifyStatus", headerName: "Verify Status", width: 100 },
  {
    field: "pan",
    headerName: "Pan",
    type: "string",
    width: 120,
    renderCell: (params) => (
      <MaskedData data={params.value} type={MaskType.PAN} />
    ),
  },
  {
    field: "verifier",
    headerName: "Verifier",
    width: 80,
  },
  {
    field: "applicantname",
    headerName: "Applicant Name",
    width: 170,
  },
  {
    field: "mobile",
    headerName: "Mobile",
    width: 110,
    renderCell: (params) => (
      <MaskedData data={params.value} type={MaskType.MOBILE} />
    ),
  },
  {
    field: "email",
    headerName: "Email",
    width: 160,
    renderCell: (params) => (
      <MaskedData data={params.value} type={MaskType.EMAIL} />
    ),
  },
  {
    field: "dob",
    headerName: "DOB",
    width: 120,
    type: "dateTime",
  },
  {
    field: "kraverified",
    headerName: "Kra Verified",
    width: 120,
  },
  {
    field: "location",
    headerName: "Location",
    width: 70,
  },
  {
    field: "promocode",
    headerName: "Promo Code",
    width: 100,
  },
  {
    field: "referalcode",
    headerName: "Referal Code",
    width: 100,
  },
];

export const rows = [
  // {
  //   id:
  //   show:
  //   device:
  //   verifyStatus:
  //   pan:
  //   verifier:
  //   applicantname:
  //   mobile:
  //   email:
  //   dob:
  //   kraverified:
  //   location:
  //   promocode:
  //   referalcode:
  // },

  {
    id: 1,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 2,
    show: "link",
    device: "desktop",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 3,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 4,
    show: "https://www.figma.com/file/X46fUMn6rbNTLShWOtp1UV/E-KYC-SMC?node-id=57%3A1772",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 5,
    show: "link",
    device: "desktop",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 6,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 7,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 8,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 9,
    show: "link",
    device: "desktop",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 10,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 11,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 12,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 13,
    show: "link",
    device: "desktop",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 14,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 15,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 16,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 17,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 18,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 19,
    show: "link",
    device: "desktop",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 20,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 21,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 22,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 23,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 24,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 25,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 26,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 27,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 28,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 29,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 30,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 31,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 32,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 33,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 34,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 35,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 36,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 37,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 38,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 39,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 40,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 41,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 42,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 43,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 44,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 45,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
  {
    id: 46,
    show: "link",
    device: "mobile",
    verifyStatus: "EsignDone",
    pan: "ASXPC3249C",
    verifier: "TANIKAB",
    applicantname: "DEEPAK CHANDRABHU",
    mobile: "8828396108",
    email: "DEEPAKCHATURVEDI7977...",
    dob: randomCreatedDate(),
    kraverified: "KRA VERIFIED",
    location: "BOM",
    promocode: "KVBFREE",
    referalcode: "G7458",
  },
];
